In [ ]:
#Files

#train.csv - the training dataset; Listening_Time_minutes is the target
#test.csv - the test dataset; your objective is to predict the Listening_Time_minutes for each row
#sample_submission.csv - a sample submission file in the correct format.

In [ ]:
#Importing file form google dirve
# mounting google drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#change dataset source

In [ ]:
#reading data

df1_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/playground/train.csv')
df1_train

df1_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/playground/test.csv')
df1_test

df1_sample = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submission.csv')
df1_sample

            ID  Predicted
0       750000  55.713550
1       750001  18.076439
2       750002  49.840973
3       750003  80.034630
4       750004  48.118603
...        ...        ...
249995  999995  11.866000
249996  999996  57.926254
249997  999997   6.701472
249998  999998  74.364426
249999  999999  57.134550

[250000 rows x 2 columns]

In [ ]:
df1_target = df1_train['Listening_Time_minutes']

In [ ]:
df1_train.head()

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Listening_Time_minutes
0,0,Mystery Matters,Episode 98,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive,31.41998
1,1,Joke Junction,Episode 26,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative,88.01241
2,2,Study Sessions,Episode 16,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative,44.92531
3,3,Digital Digest,Episode 45,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive,46.27824
4,4,Mind & Body,Episode 86,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral,75.61031

In [ ]:
df1_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           750000 non-null  int64
 1   Podcast_Name                 750000 non-null  object
 2   Episode_Title                750000 non-null  object
 3   Episode_Length_minutes       662907 non-null  float64
 4   Genre                        750000 non-null  object
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object
 7   Publication_Time             750000 non-null  object
 8   Guest_Popularity_percentage  603970 non-null  float64
 9   Number_of_Ads                749999 non-null  float64
 10  Episode_Sentiment            750000 non-null  object
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB

In [ ]:
#check for missing values

df1_train.isnull().sum()/len(df1_train)*100

id                              0.000000
Podcast_Name                    0.000000
Episode_Title                   0.000000
Episode_Length_minutes         11.612400
Genre                           0.000000
Host_Popularity_percentage      0.000000
Publication_Day                 0.000000
Publication_Time                0.000000
Guest_Popularity_percentage    19.470667
Number_of_Ads                   0.000133
Episode_Sentiment               0.000000
Listening_Time_minutes          0.000000
dtype: float64

In [ ]:
#dropping podcast_name , episodde_title and listening_time_minuees

df1_train.drop(['id','Podcast_Name', 'Episode_Title', 'Listening_Time_minutes'], axis=1, inplace=True)

In [ ]:
#segregating the data into categorical and numerical column

L1 = [df1_train.select_dtypes(include='object').columns]
L2 = [df1_train.select_dtypes(exclude='object').columns]

In [ ]:
L1 = list(L1[0])
L2 = list(L2[0])

print(L2)
print(L1)

['Episode_Length_minutes', 'Host_Popularity_percentage', 'Guest_Popularity_percentage', 'Number_of_Ads']
['Genre', 'Publication_Day', 'Publication_Time', 'Episode_Sentiment']

In [ ]:
df1_train.head()

,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
0,NaN,True Crime,74.81,Thursday,Night,NaN,0.0,Positive
1,119.80,Comedy,66.95,Saturday,Afternoon,75.95,2.0,Negative
2,73.90,Education,69.97,Tuesday,Evening,8.97,0.0,Negative
3,67.17,Technology,57.22,Monday,Morning,78.70,2.0,Positive
4,110.51,Health,80.07,Monday,Afternoon,58.68,3.0,Neutral

In [ ]:
#scaling the numerical columns and categorical columns

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
# Define columns
num_cols = L2
cat_cols = L1


# Create ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_cols)
])

# Fit and transform
df2_train_processed = preprocessor.fit_transform(df1_train)

# Get one-hot column names
cat_encoded_columns = preprocessor.named_transformers_['cat'].get_feature_names_out(list(cat_cols))

# Combine all column names
all_columns = num_cols + list(cat_encoded_columns)

# Create a new DataFrame with readable column names
df_final = pd.DataFrame(df2_train_processed, columns=all_columns)

print(df_final)

        Episode_Length_minutes  Host_Popularity_percentage  \
0                          NaN                    0.653611
1                     1.677160                    0.309976
2                     0.284968                    0.442009
3                     0.080840                   -0.115415
4                     1.395385                    0.883576
...                        ...                         ...
749995                0.338350                    0.415340
749996                0.341080                   -1.077682
749997               -1.016839                    0.818434
749998                1.348979                   -0.632617
749999               -1.225516                   -1.635543

        Guest_Popularity_percentage  Number_of_Ads  Genre_Business  \
0                               NaN      -1.171766             0.0
1                          0.833481       0.565657             0.0
2                         -1.520724      -1.171766             0.0
3                          0.930138       0.565657             0.0
4                          0.226477       1.434369             0.0
...                             ...            ...             ...
749995                          NaN      -1.171766             0.0
749996                          NaN       0.565657             1.0
749997                     1.147703      -1.171766             0.0
749998                     1.442242      -1.171766             0.0
749999                    -0.545370      -1.171766             0.0

        Genre_Comedy  Genre_Education  Genre_Health  Genre_Lifestyle  \
0                0.0              0.0           0.0              0.0
1                1.0              0.0           0.0              0.0
2                0.0              1.0           0.0              0.0
3                0.0              0.0           0.0              0.0
4                0.0              0.0           1.0              0.0
...              ...              ...           ...              ...
749995           0.0              1.0           0.0              0.0
749996           0.0              0.0           0.0              0.0
749997           0.0              0.0           0.0              1.0
749998           0.0              0.0           0.0              1.0
749999           0.0              0.0           0.0              0.0

        Genre_Music  ...  Publication_Day_Thursday  Publication_Day_Tuesday  \
0               0.0  ...                       1.0                      0.0
1               0.0  ...                       0.0                      0.0
2               0.0  ...                       0.0                      1.0
3               0.0  ...                       0.0                      0.0
4               0.0  ...                       0.0                      0.0
...             ...  ...                       ...                      ...
749995          0.0  ...                       0.0                      0.0
749996          0.0  ...                       0.0                      0.0
749997          0.0  ...                       1.0                      0.0
749998          0.0  ...                       1.0                      0.0
749999          0.0  ...                       0.0                      0.0

        Publication_Day_Wednesday  Publication_Time_Afternoon  \
0                             0.0                         0.0
1                             0.0                         1.0
2                             0.0                         0.0
3                             0.0                         0.0
4                             0.0                         1.0
...                           ...                         ...
749995                        0.0                         0.0
749996                        0.0                         0.0
749997                        0.0                         0.0
749998                        0.0                         0.0
749999                        0.0                         0.0

        Publication_Time_Evening  Publication_Time_Morning  \
0                            0.0                       0.0
1                            0.0                       0.0
2                            1.0                       0.0
3                            0.0                       1.0
4                            0.0                       0.0
...                          ...                       ...
749995                       0.0                       1.0
749996                       0.0                       0.0
749997                       0.0                       1.0
749998                       0.0                       1.0
749999                       0.0                       0.0

        Publication_Time_Night  Episode_Sentiment_Negative  \
0                          1.0                         0.0
1                          0.0                         1.0
2                          0.0                         1.0
3                          0.0                         0.0
4                          0.0                         0.0
...                        ...                         ...
749995                     0.0                         1.0
749996                     1.0                         0.0
749997                     0.0                         1.0
749998                     0.0                         1.0
749999                     1.0                         0.0

        Episode_Sentiment_Neutral  Episode_Sentiment_Positive
0                             0.0                         1.0
1                             0.0                         0.0
2                             0.0                         0.0
3                             0.0                         1.0
4                             1.0                         0.0
...                           ...                         ...
749995                        0.0                         0.0
749996                        1.0                         0.0
749997                        0.0                         0.0
749998                        0.0                         0.0
749999                        1.0                         0.0

[750000 rows x 28 columns]

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
# we will be using KNN to impute for the missing values in column Episode_Length_minutes and Guest_Popularity_percentage

# Initialize KNN Imputer
#imputer = KNNImputer(n_neighbors=2)

# Fit and transform
#df1_train_imputed = pd.DataFrame(imputer.fit_transform(df2_train_processed), columns=df2_train_processed.columns)

In [ ]:
#checking for missing values

#df1_train_imputed.isnull().sum() / len(df1_train_imputed) * 100

In [ ]:
df_final.head()

,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Genre_Business,Genre_Comedy,Genre_Education,Genre_Health,Genre_Lifestyle,Genre_Music,...,Publication_Day_Thursday,Publication_Day_Tuesday,Publication_Day_Wednesday,Publication_Time_Afternoon,Publication_Time_Evening,Publication_Time_Morning,Publication_Time_Night,Episode_Sentiment_Negative,Episode_Sentiment_Neutral,Episode_Sentiment_Positive
0,NaN,0.653611,NaN,-1.171766,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.677160,0.309976,0.833481,0.565657,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.284968,0.442009,-1.520724,-1.171766,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.080840,-0.115415,0.930138,0.565657,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.395385,0.883576,0.226477,1.434369,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# doing the transformations that we did on train data

In [ ]:
#dropping columns which we dorpped in df1_train

df1_test.drop(['id','Podcast_Name', 'Episode_Title'], axis=1, inplace=True)

In [ ]:
df1_test.head()

,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
0,78.96,Education,38.11,Saturday,Evening,53.33,1.0,Neutral
1,27.87,Music,71.29,Sunday,Morning,NaN,0.0,Neutral
2,69.10,Comedy,67.89,Friday,Evening,97.51,0.0,Positive
3,115.39,Comedy,23.40,Sunday,Morning,51.75,2.0,Positive
4,72.32,Lifestyle,58.10,Wednesday,Morning,11.30,2.0,Neutral

In [ ]:
# Transform test data using the already-fitted preprocessor
df2_test_processed = preprocessor.transform(df1_test)

# Create final DataFrame with correct column names
df_test_final = pd.DataFrame(df2_test_processed, columns=all_columns)

print(df_test_final.head())

   Episode_Length_minutes  Host_Popularity_percentage  \
0                0.438442                   -0.950895
1               -1.111168                    0.499718
2                0.139379                    0.351072
3                1.543400                   -1.594009
4                0.237045                   -0.076942

   Guest_Popularity_percentage  Number_of_Ads  Genre_Business  Genre_Comedy  \
0                     0.038436      -0.303054             0.0           0.0
1                          NaN      -1.171766             0.0           0.0
2                     1.591269      -1.171766             0.0           1.0
3                    -0.017098       0.565657             0.0           1.0
4                    -1.438829       0.565657             0.0           0.0

   Genre_Education  Genre_Health  Genre_Lifestyle  Genre_Music  ...  \
0              1.0           0.0              0.0          0.0  ...
1              0.0           0.0              0.0          1.0  ...
2              0.0           0.0              0.0          0.0  ...
3              0.0           0.0              0.0          0.0  ...
4              0.0           0.0              1.0          0.0  ...

   Publication_Day_Thursday  Publication_Day_Tuesday  \
0                       0.0                      0.0
1                       0.0                      0.0
2                       0.0                      0.0
3                       0.0                      0.0
4                       0.0                      0.0

   Publication_Day_Wednesday  Publication_Time_Afternoon  \
0                        0.0                         0.0
1                        0.0                         0.0
2                        0.0                         0.0
3                        0.0                         0.0
4                        1.0                         0.0

   Publication_Time_Evening  Publication_Time_Morning  Publication_Time_Night  \
0                       1.0                       0.0                     0.0
1                       0.0                       1.0                     0.0
2                       1.0                       0.0                     0.0
3                       0.0                       1.0                     0.0
4                       0.0                       1.0                     0.0

   Episode_Sentiment_Negative  Episode_Sentiment_Neutral  \
0                         0.0                        1.0
1                         0.0                        1.0
2                         0.0                        0.0
3                         0.0                        0.0
4                         0.0                        1.0

   Episode_Sentiment_Positive
0                         0.0
1                         0.0
2                         1.0
3                         1.0
4                         0.0

[5 rows x 28 columns]

In [ ]:
df_test_final.head()

,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Genre_Business,Genre_Comedy,Genre_Education,Genre_Health,Genre_Lifestyle,Genre_Music,...,Publication_Day_Thursday,Publication_Day_Tuesday,Publication_Day_Wednesday,Publication_Time_Afternoon,Publication_Time_Evening,Publication_Time_Morning,Publication_Time_Night,Episode_Sentiment_Negative,Episode_Sentiment_Neutral,Episode_Sentiment_Positive
0,0.438442,-0.950895,0.038436,-0.303054,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-1.111168,0.499718,NaN,-1.171766,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.139379,0.351072,1.591269,-1.171766,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,1.543400,-1.594009,-0.017098,0.565657,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.237045,-0.076942,-1.438829,0.565657,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
X1 = df_final.copy()
y = df1_target.copy()

# change datasource

In [ ]:
df2_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/playground/test.csv')
df2_test

,id,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
0,750000,Educational Nuggets,Episode 73,78.96,Education,38.11,Saturday,Evening,53.33,1.0,Neutral
1,750001,Sound Waves,Episode 23,27.87,Music,71.29,Sunday,Morning,NaN,0.0,Neutral
2,750002,Joke Junction,Episode 11,69.10,Comedy,67.89,Friday,Evening,97.51,0.0,Positive
3,750003,Comedy Corner,Episode 73,115.39,Comedy,23.40,Sunday,Morning,51.75,2.0,Positive
4,750004,Life Lessons,Episode 50,72.32,Lifestyle,58.10,Wednesday,Morning,11.30,2.0,Neutral
...,...,...,...,...,...,...,...,...,...,...,...
249995,999995,Mind & Body,Episode 100,21.05,Health,65.77,Saturday,Evening,96.40,3.0,Negative
249996,999996,Joke Junction,Episode 85,85.50,Comedy,41.47,Saturday,Night,30.52,2.0,Negative
249997,999997,Joke Junction,Episode 63,12.11,Comedy,25.92,Thursday,Evening,73.69,1.0,Neutral
249998,999998,Market Masters,Episode 46,113.46,Business,43.47,Friday,Night,93.59,3.0,Positive
249999,999999,Brain Boost,Episode 46,78.05,Education,41.72,Friday,Morning,50.77,0.0,Negative

In [ ]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline

In [ ]:
#importing random forest
from sklearn.ensemble import RandomForestRegressor

#change dataset source of output file

In [1]:
#building randome forest model
# ------------------------
# Step 4: Create model pipeline
# ------------------------
model = Pipeline(steps=[
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
])

# ------------------------
# Step 5: Train the model
# ------------------------
model.fit(X1, y)

# ------------------------
# Step 6: Predict on test data
# ------------------------
X_test = df_test_final.copy()
predictions = model.predict(X_test)

# ------------------------
# Step 7: Output predictions
# ------------------------
output_df = pd.DataFrame({
    'ID': df2_test['id'],           # Replace 'ID' with your actual ID column if needed
    'Predicted': predictions
})

#output_df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submissionrf.csv', index=False)
print("✅ Predictions saved to xgboost_predictions.csv")

'\n#building randome forest model\n# ------------------------\n# Step 4: Create model pipeline\n# ------------------------\nmodel = Pipeline(steps=[\n    (\'regressor\', RandomForestRegressor(n_estimators=100, random_state=42))\n])\n\n# ------------------------\n# Step 5: Train the model\n# ------------------------\nmodel.fit(X1, y)\n\n# ------------------------\n# Step 6: Predict on test data\n# ------------------------\nX_test = df_test_final.copy()\npredictions = model.predict(X_test)\n\n# ------------------------\n# Step 7: Output predictions\n# ------------------------\noutput_df = pd.DataFrame({\n    \'ID\': df2_test[\'id\'],           # Replace \'ID\' with your actual ID column if needed\n    \'Predicted\': predictions\n})\n\n#output_df.to_csv(r\'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submissionrf.csv\', index=False)\nprint("✅ Predictions saved to xgboost_predictions.csv")\n'

In [ ]:
'''
# ------------------------
# Step 4: Create model pipeline
# ------------------------
model = Pipeline(steps=[
    ('regressor', XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42))
])

# ------------------------
# Step 5: Train the model
# ------------------------
model.fit(X1, y)

# ------------------------
# Step 6: Predict on test data
# ------------------------
X_test = df_test_final.copy()
predictions = model.predict(X_test)

# ------------------------
# Step 7: Output predictions
# ------------------------
output_df = pd.DataFrame({
    'ID': df2_test['id'],           # Replace 'ID' with your actual ID column if needed
    'Predicted': predictions
})

#output_df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submission.csv', index=False)
print("✅ Predictions saved to xgboost_predictions.csv")
'''

✅ Predictions saved to xgboost_predictions.csv

In [ ]:
#fine tuning model

In [2]:
'''
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
import pandas as pd

# ------------------------
# Step 1: Create Base Pipeline (without preprocessor here)
# ------------------------
pipeline = Pipeline(steps=[
    ('regressor', XGBRegressor(random_state=42))
])

# ------------------------
# Step 2: Define Hyperparameter Grid
# ------------------------
param_grid = {
    'regressor__n_estimators': [100, 200],
    'regressor__max_depth': [3, 5, 7],
    'regressor__learning_rate': [0.01, 0.1, 0.2],
    'regressor__subsample': [0.8, 1]
}

# ------------------------
# Step 3: Setup GridSearchCV
# ------------------------
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='neg_root_mean_squared_error',  # use RMSE for regression
    verbose=2,
    n_jobs=-1  # Use all cores
)

# ------------------------
# Step 4: Fit GridSearch on Training Data
# ------------------------
grid_search.fit(X1, y)

print("✅ Best Params:", grid_search.best_params_)
print("🏆 Best RMSE (CV):", -grid_search.best_score_)

# ------------------------
# Step 5: Predict on Test Data with Best Estimator
# ------------------------
best_model = grid_search.best_estimator_
predictions = best_model.predict(df_test_final)

# ------------------------
# Step 6: Save Predictions
# ------------------------
output_df = pd.DataFrame({
    'id': df2_test['id'],
    'Listening_Time_minutes': predictions
})

output_df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submission1.csv', index=False)
print("✅ Predictions saved with GridSearch best model!")
'''

'\nfrom sklearn.model_selection import GridSearchCV\nfrom xgboost import XGBRegressor\nfrom sklearn.pipeline import Pipeline\nimport pandas as pd\n\n# ------------------------\n# Step 1: Create Base Pipeline (without preprocessor here)\n# ------------------------\npipeline = Pipeline(steps=[\n    (\'regressor\', XGBRegressor(random_state=42))\n])\n\n# ------------------------\n# Step 2: Define Hyperparameter Grid\n# ------------------------\nparam_grid = {\n    \'regressor__n_estimators\': [100, 200],\n    \'regressor__max_depth\': [3, 5, 7],\n    \'regressor__learning_rate\': [0.01, 0.1, 0.2],\n    \'regressor__subsample\': [0.8, 1]\n}\n\n# ------------------------\n# Step 3: Setup GridSearchCV\n# ------------------------\ngrid_search = GridSearchCV(\n    estimator=pipeline,\n    param_grid=param_grid,\n    cv=5,\n    scoring=\'neg_root_mean_squared_error\',  # use RMSE for regression\n    verbose=2,\n    n_jobs=-1  # Use all cores\n)\n\n# ------------------------\n# Step 4: Fit GridSearch on Training Data\n# ------------------------\ngrid_search.fit(X1, y)\n\nprint("✅ Best Params:", grid_search.best_params_)\nprint("🏆 Best RMSE (CV):", -grid_search.best_score_)\n\n# ------------------------\n# Step 5: Predict on Test Data with Best Estimator\n# ------------------------\nbest_model = grid_search.best_estimator_\npredictions = best_model.predict(df_test_final)\n\n# ------------------------\n# Step 6: Save Predictions\n# ------------------------\noutput_df = pd.DataFrame({\n    \'id\': df2_test[\'id\'],\n    \'Listening_Time_minutes\': predictions\n})\n\noutput_df.to_csv(r\'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submission1.csv\', index=False)\nprint("✅ Predictions saved with GridSearch best model!")\n'

In [ ]:
pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.15.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.13.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from scikeras.wrappers import KerasRegressor
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import pandas as pd

In [ ]:
# ------------------------
# Step 0: Define Neural Net Model Builder
# ------------------------
def build_model(hidden_layer_1=64, hidden_layer_2=32, learning_rate=0.001):
    model = Sequential()
    model.add(Dense(hidden_layer_1, activation='relu', input_shape=(X1.shape[1],)))
    model.add(Dense(hidden_layer_2, activation='relu'))
    model.add(Dense(1))  # regression output
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mean_squared_error')
    return model

# ------

In [ ]:
# Step 1: Create Pipeline
# ------------------------
pipeline = Pipeline(steps=[
    ('scaler', StandardScaler()),  # recommended for neural nets
    ('regressor', KerasRegressor(model=build_model, verbose=0, random_state=42))
])

In [ ]:
param_grid = {
    'regressor__model__hidden_layer_1': [64,128],
    'regressor__model__hidden_layer_2': [32,64],
    'regressor__model__learning_rate': [0.001, 0.01],
    'regressor__batch_size': [32,64],
    'regressor__epochs': [3]
}

In [ ]:
# ------------------------
# Step 3: GridSearchCV
# ------------------------
search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    verbose=2
)
# --

In [ ]:
print(X1.isnull().sum())
print(df_test_final.isnull().sum())

Episode_Length_minutes          87093
Host_Popularity_percentage          0
Guest_Popularity_percentage    146030
Number_of_Ads                       1
Genre_Business                      0
Genre_Comedy                        0
Genre_Education                     0
Genre_Health                        0
Genre_Lifestyle                     0
Genre_Music                         0
Genre_News                          0
Genre_Sports                        0
Genre_Technology                    0
Genre_True Crime                    0
Publication_Day_Friday              0
Publication_Day_Monday              0
Publication_Day_Saturday            0
Publication_Day_Sunday              0
Publication_Day_Thursday            0
Publication_Day_Tuesday             0
Publication_Day_Wednesday           0
Publication_Time_Afternoon          0
Publication_Time_Evening            0
Publication_Time_Morning            0
Publication_Time_Night              0
Episode_Sentiment_Negative          0
Episode_Sentiment_Neutral           0
Episode_Sentiment_Positive          0
dtype: int64
Episode_Length_minutes         28736
Host_Popularity_percentage         0
Guest_Popularity_percentage    48832
Number_of_Ads                      0
Genre_Business                     0
Genre_Comedy                       0
Genre_Education                    0
Genre_Health                       0
Genre_Lifestyle                    0
Genre_Music                        0
Genre_News                         0
Genre_Sports                       0
Genre_Technology                   0
Genre_True Crime                   0
Publication_Day_Friday             0
Publication_Day_Monday             0
Publication_Day_Saturday           0
Publication_Day_Sunday             0
Publication_Day_Thursday           0
Publication_Day_Tuesday            0
Publication_Day_Wednesday          0
Publication_Time_Afternoon         0
Publication_Time_Evening           0
Publication_Time_Morning           0
Publication_Time_Night             0
Episode_Sentiment_Negative         0
Episode_Sentiment_Neutral          0
Episode_Sentiment_Positive         0
dtype: int64

In [ ]:
X1 = X1.fillna(X1.mean())
df_test_final = df_test_final.fillna(X1.mean())  # use train mean for test

#change output datasource

In [ ]:
# ------------------------
# Step 4: Fit on Training Data
# ------------------------
search.fit(X1, y)

print("✅ Best Params:", search.best_params_)
print("🏆 Best RMSE (CV):", -search.best_score_)

# ------------------------
# Step 5: Predict on Test Data
# ------------------------
best_model = search.best_estimator_
predictions = best_model.predict(df_test_final)

# ------------------------
# Step 6: Save Predictions
# ------------------------
output_df = pd.DataFrame({
    'id': df2_test['id'],
    'Listening_Time_minutes': predictions
})

output_df.to_csv(r'/content/drive/MyDrive/Colab Notebooks/Data/playground/sample_submission_nn.csv', index=False)
print("✅ Predictions saved with Neural Network model!")

Fitting 3 folds for each of 4 candidates, totalling 12 fits

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 4 is smaller than n_iter=10. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

✅ Best Params: {'regressor__model__learning_rate': 0.001, 'regressor__model__hidden_layer_2': 16, 'regressor__model__hidden_layer_1': 32, 'regressor__epochs': 3, 'regressor__batch_size': 8}
🏆 Best RMSE (CV): nan

AttributeError: 'super' object has no attribute '__sklearn_tags__'